services:
  db:
    image: postgres:latest
    container_name: tona_db
    restart: unless-stopped
    env_file:
      - ./postgres-db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile
    container_name: tona_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:80"
    env_file:
      - ./fastapi-backend/.env

  frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    container_name: tona_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    env_file:
      - ./vue-frontend/.env

volumes:
  postgres_data: